### ISSUE TITLE
The defaultColor is not working.

### ISSUE THREAD

**Issue by dreamer01** [holmansv/react-native-color-palette#11]
Hey,

Its great componet you have created here. I was looking into your code and I found there is warning for `selectedColor` prop in Uncontrolled component as no color is selected by default.

This is because `defaultColor` was not set correctly. And also there was few edge cases missings.

I have refracted the logic for the same and taken into few edge cases and thus now there is no warning.
I would like to create a **PR** for same, if you are accepting any contributions.

Once again great work.
Thanks.

**Comment by JuanpaG94** [comment]
Same here. Can confirm it's an actual issue.

**Comment by vincentvella** [comment]
@dreamer01 feel free to submit a PR

**Comment by dreamer01** [comment]
@vincentvella I had created a [PR](https://github.com/holmansv/react-native-color-palette/pull/12) please take a look.

**Comment by vincentvella** [comment]
Fixed in v2.2.0
Thanks for the PR.
Please confirm the new release is working so I can close this issue.
