### ISSUE TITLE
Rename componentWillReceiveProps

### ISSUE THREAD

**Issue by cristianoccazinsp** [holmansv/react-native-color-palette#7]
Please migrate unsafe/deprecated methods to their respective UNSAFE_* variant in order to prepare for React 17

**Comment by JuanpaG94** [comment]
Please migrate this. In the next major version "componentWillReceiveProps" is going to be removed. Use static getDerivedStateFromprops insead.

https://fb.me/react-async-component-lifecycle-hooks

**Comment by vincentvella** [comment]
Addressed in the latest release.
Can you confirm with v2.1.0?

**Comment by JuanpaG94** [comment]
Thanks for addressing this @vincentvella 
Confirmed it's now working properly, but now there's a problem with defaultColor prop
More info on this issue https://github.com/holmansv/react-native-color-palette/issues/11

**Comment by vincentvella** [comment]
Closing this issue. #11 has also been addressed.
